output_root: "outputs"
output_version: "baseline"
backup_name: "weights"
log_name: "logs"

labels: ["car","truck","person","bus"]

data_root_dir: "/media/eric/Daten/KITTI/VOCdevkit/onedet_cache"

train:
    dataset: "train"
    stdout: False
    gpus: "0"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.001
    lr_steps: [5000,10000,40000,60000,80000, 120000,140000]
    lr_rates: [0.0001,0.0005,0.0002,0.0001,0.0001, 0.0001, 0.00001]
    max_batches: 160200
    resize_interval: 500

    backup_interval: 50
    backup_steps: [500, 500]
    backup_rates: [1000, 200]

    input_shape: [608, 608]
    batch_size: 8
    mini_batch_size: 4
    weights: ~

test:
    dataset: "test"
    stdout: True
    gpus: "0"
    nworkers: 8
    pin_mem: True

    input_shape: [544, 544]
    batch_size: 4
    weights: "outputs/CutinPredNet/baseline/weights/e2e_with_aug.pt"

    conf_thresh: 0.005
    nms_thresh: 0.45

    results: "results"

speed:
    gpus: "0"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]